DROP TABLE IF EXISTS SYS_BIZ_LOG;
CREATE TABLE SYS_BIZ_LOG (
	ID varchar(32) NOT NULL COMMENT '编号',
	ENTITY varchar(40) NOT NULL COMMENT '操作实体',
	ENTITY_ID varchar(32) NOT NULL COMMENT '实体编号',
	OPT_TYPE varchar(1) NOT NULL COMMENT '操作类型',
	OPERATE varchar(30) NOT NULL COMMENT '具体操作',
	OPT_IP varchar(20) COMMENT '操作IP地址',
	NEW_VALUE text COMMENT '新数据',
	OLD_VALUE text COMMENT '旧数据',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
	ID varchar(32) NOT NULL COMMENT '编号',
	CATEGORY varchar(3) NOT NULL COMMENT '类型',
	NAME varchar(80) NOT NULL COMMENT '名称',
	DESCRIPTION varchar(255) NOT NULL COMMENT '备注',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
	LAST_MNT_OPID varchar(40) COMMENT '最后修改人',
	LAST_MNT_TS datetime(6) COMMENT '最后修改时间',
	VERSION_CT decimal(17,0) DEFAULT '0' COMMENT '版本号',
PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS GL_CONFIG;
CREATE TABLE GL_CONFIG (
	CFG_KEY varchar(32) NOT NULL COMMENT '参数编号',
	CFG_VALUE varchar(40) NOT NULL COMMENT '参数值',
	CFG_TYPE varchar(1) NOT NULL COMMENT '参数类型',
	MEMO varchar(100) NOT NULL COMMENT '参数备注',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
	LAST_MNT_OPID varchar(40) COMMENT '最后修改人',
	LAST_MNT_TS datetime(6) COMMENT '最后修改时间',
	VERSION_CT decimal(17,0) DEFAULT '0' COMMENT '版本号',
PRIMARY KEY (CFG_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS GL_DICT;
CREATE TABLE GL_DICT (
	ID varchar(32) NOT NULL COMMENT 'id',
	CATEGORY varchar(20) NOT NULL COMMENT '类型',
	DICT_CODE varchar(100) NOT NULL COMMENT '字典编号',
	DICT_TEXT varchar(100) NOT NULL COMMENT '字典内容',
	DICT_TEXT_FULL varchar(200) NOT NULL COMMENT '字典内容详情',
	PARENT_DICT_CODE varchar(100) NOT NULL COMMENT '父节点编号',
	ENABLE_FLG varchar(1) NOT NULL COMMENT '是否可用,1:是,2:否',
	LEAF_FLG varchar(1) NOT NULL COMMENT '是否子节点,1:是,2:否',
	DICT_ORD decimal(17,0) NOT NULL COMMENT '字典顺序',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS GL_FILE;
CREATE TABLE GL_FILE (
	FILE_ID varchar(32) NOT NULL COMMENT '文件Id',
	FILE_CODE varchar(32) NOT NULL COMMENT '文件编码',
	FILE_NAME varchar(255) NOT NULL COMMENT '文件名',
	FILE_PATH varchar(255) NOT NULL COMMENT '文件路径',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
PRIMARY KEY (FILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS SYS_PERM;
CREATE TABLE SYS_PERM (
	PERM_ID varchar(32) NOT NULL COMMENT '功能权限编号',
	PERM_CODE varchar(32) NOT NULL COMMENT '功能权限代码',
	PERM_NAME varchar(32) NOT NULL COMMENT '功能权限名称',
	PERM_DESC varchar(32) COMMENT '功能权限说明',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
	LAST_MNT_OPID varchar(40) COMMENT '最后修改人',
	LAST_MNT_TS datetime(6) COMMENT '最后修改时间',
	VERSION_CT decimal(17,0) DEFAULT '0' COMMENT '版本号',
PRIMARY KEY (PERM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS SYS_ROLE_PERM;
CREATE TABLE SYS_ROLE_PERM (
	ROLE_ID varchar(32) NOT NULL COMMENT '角色ID',
	PERM_ID varchar(32) NOT NULL COMMENT '权限ID',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
	LAST_MNT_OPID varchar(40) COMMENT '最后修改人',
	LAST_MNT_TS datetime(6) COMMENT '最后修改时间',
	VERSION_CT decimal(17,0) DEFAULT '0' COMMENT '版本号',
PRIMARY KEY (ROLE_ID,PERM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS SYS_ROLE;
CREATE TABLE SYS_ROLE (
	ROLE_ID varchar(32) NOT NULL COMMENT '角色编号',
	ROLE_CODE varchar(20) NOT NULL COMMENT '角色代码',
	ROLE_NAME varchar(60) NOT NULL COMMENT '角色名称',
	ROLE_DESC varchar(200) COMMENT '角色备注',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
	LAST_MNT_OPID varchar(40) COMMENT '最后修改人',
	LAST_MNT_TS datetime(6) COMMENT '最后修改时间',
	VERSION_CT decimal(17,0) DEFAULT '0' COMMENT '版本号',
PRIMARY KEY (ROLE_ID),
UNIQUE KEY ROLE_CODE (ROLE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS SYS_USER_ROLE;
CREATE TABLE SYS_USER_ROLE (
	USER_ID varchar(32) NOT NULL COMMENT '用户编号',
	ROLE_ID varchar(32) NOT NULL COMMENT '角色编号',
	STATUS varchar(1) NOT NULL DEFAULT '1' COMMENT '0-待生效, 1-已生效，默认1-已生效',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
	LAST_MNT_OPID varchar(40) COMMENT '最后修改人',
	LAST_MNT_TS datetime(6) COMMENT '最后修改时间',
	VERSION_CT decimal(17,0) DEFAULT '0' COMMENT '版本号',
PRIMARY KEY (USER_ID,ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS SYS_PRSNL_EXT;
CREATE TABLE SYS_PRSNL_EXT (
	USER_ID varchar(32) NOT NULL COMMENT '用户编号',
	SNAME varchar(60) COMMENT '用户姓名',
	BIRTH_DT varchar(10) COMMENT '出生日期',
	SEX varchar(10) COMMENT '性别',
	ID_TYPE varchar(10) COMMENT '证件类型',
	ID_NO varchar(100) COMMENT '证件号码',
	ID_IMG_1 varchar(100) COMMENT '证件正面图片',
	ID_IMG_2 varchar(100) COMMENT '证件反面图片',
	ID_START_DT varchar(10) COMMENT '身份证有效期开始日期yyyy-MM-dd',
	ID_END_DT varchar(10) COMMENT '身份证有效期截止日期yyyy-MM-dd',
	JOB_TYPE varchar(10) COMMENT '工作类型',
	JOB_DESC varchar(100) COMMENT '工作简介',
	EDU_TYPE varchar(10) COMMENT '教育程度',
	TEL varchar(20) COMMENT '联系电话',
	QQ varchar(20) COMMENT 'QQ号码',
	WX varchar(40) COMMENT '微信号码',
	FAX varchar(20) COMMENT '传真号码',
	ZIP_CODE varchar(20) COMMENT '邮政编码',
	ADDR varchar(200) COMMENT '联系地址',
	WORK_UNIT varchar(100) COMMENT '工作单位',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
	LAST_MNT_OPID varchar(40) COMMENT '最后修改人',
	LAST_MNT_TS datetime(6) COMMENT '最后修改时间',
	VERSION_CT decimal(17,0) DEFAULT '0' COMMENT '版本号',
PRIMARY KEY (USER_ID),
UNIQUE KEY ID_NO (ID_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER (
	USER_ID varchar(32) NOT NULL COMMENT '用户编号',
	NICK_NAME varchar(20) NOT NULL COMMENT '用户名',
	SNAME varchar(40) NOT NULL COMMENT '用户姓名',
	PASSWORD varchar(100) NOT NULL COMMENT '密码',
	STATUS varchar(2) NOT NULL COMMENT '状态:1 Active, 2 Inactive, 3 Cancelled',
	EMAIL varchar(100) COMMENT '邮箱',
	MOBILE varchar(20) NOT NULL COMMENT '手机号',
	USER_TYPE varchar(2) NOT NULL COMMENT '用户类型',
	REGION varchar(30) COMMENT '所属区域',
	ICON_FILE_ID varchar(100) COMMENT '用户头像',
	LAST_LOGIN_TS datetime(6) COMMENT '最后登录时间',
	LOGIN_FAIL_CT decimal(17,0) COMMENT '登录失败次数',
	LAST_LOGIN_FAIL_TS datetime(6) COMMENT '最后登陆失败时间',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
	LAST_MNT_OPID varchar(40) COMMENT '最后修改人',
	LAST_MNT_TS datetime(6) COMMENT '最后修改时间',
	VERSION_CT decimal(17,0) DEFAULT '0' COMMENT '版本号',
PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS SYS_USER_VER_JNL;
CREATE TABLE SYS_USER_VER_JNL (
	JNL_NO varchar(32) NOT NULL COMMENT '流水号',
	USER_ID varchar(32) NOT NULL COMMENT '用户编号',
	STATUS varchar(1) NOT NULL COMMENT '验证码状态',
	MOBILE varchar(20) NOT NULL COMMENT '手机号',
	VER_CODE varchar(100) NOT NULL COMMENT '验证码',
	VER_END_DTTM decimal(17,0) NOT NULL COMMENT '验证码失效时间戳',
	CREATE_OPID varchar(40) NOT NULL COMMENT '创建人',
	CREATE_TS datetime(6) NOT NULL COMMENT '创建时间',
	LAST_MNT_OPID varchar(40) COMMENT '最后修改人',
	LAST_MNT_TS datetime(6) COMMENT '最后修改时间',
	VERSION_CT decimal(17,0) DEFAULT '0' COMMENT '版本号',
PRIMARY KEY (JNL_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
